### ISSUE TITLE
Second Email

### ISSUE THREAD

**Issue by PaoloB** [oveleon/contao-company-bundle#1]
Hi, is possible add a second email field?

**Comment by PaoloB** [comment]
It is also possible to create two generic fields.
In Italy it is mandatory to publish some tax data on the site.

They could be two text fields, like the company name.
They could be called Notes 1 and Notes 2.

Thanks

**Comment by eki89** [comment]
Hey PaoloB,

I'll add the fields companyEmail2, companyInfo and companyInfo2. Are 255 chars enougth for your tax data?

**Comment by PaoloB** [comment]
Yes, 255 characters are enough.
Thanks

**Comment by eki89** [comment]
I've released a new version today with an additional field email2 and two additional fields info and info2. You can retrieve these data as insert tags as well.
