### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Ma3xl3** [oveleon/contao-company-bundle#10]
Hi. 
Thanks for your bundle.

Is it possible to add PHP 8 Support?
Probably you only have to extend the composer.json with `"php":">=7.1"` or `"php":"^7.1|^8.0"`

Best regards

**Comment by zoglo** [comment]
Hello @Ma3xl3,

updating the company bundle to PHP8 is currently not possible due to requiring https://github.com/menatwork/contao-multicolumnwizard-bundle/ for the social media icons. 

We are planning to remove the dependency in a next update to make PHP8 compatibility possible.

**Comment by Ma3xl3** [comment]
Hello again.

Thanks for your response.

I forked your bundle and tried it with php 8 and contao 4.9 without any problems -> https://github.com/Ma3xl3/contao-company-bundle

As i can see the multicolumnwizard-bundle supports php 8.

Just my 2 cents 😁

**Comment by zoglo** [comment]
Hello @Ma3xl3 

the new version supports PHP8 and up to Contao 4.12:

https://github.com/oveleon/contao-company-bundle/releases/tag/1.3.0

**Comment by Ma3xl3** [comment]
Thx a lot.
I will try it the next few days 😊
