### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by Manfred-Gipp** [oveleon/contao-company-bundle#29]
Wie sieht es mit der Mehrsprachigkeit aus? 
Insbesondere, wenn die Firma in den verschiedenen Lokationen, unterschiedliche Adressen hat?
Ist so eine Idee schon mal aufgekommen?
Anstatt das bei den Einstellungen zu pflegen, wäre das vielleicht besser im Seitentyp "Website-Startseite".

**Comment by zoglo** [comment]
@Manfred-Gipp
The settings are also located within a root page, these always overwrite those in the system settings.

The feature has been implemented for quite a few years.
